project:
  type: website
date: last-modified 
website:
  title: "neelsmith"
  navbar:
    background: primary
    search: true
    left:
      - href: index.qmd
        text: Home
      - text: "Digital scholarship"
        file: digschol/index.qmd     
      - text: "Why Julia?"
        file: julia.qmd
      - about.qmd
  sidebar:
    - title: "Digital scholarship"
      contents: 
        - digschol/index.qmd

    - title: "Personal"
      contents:
        - personal/index.qmd
        - personal/white.qmd
        - personal/juliagen.qmd


format:
  html:
    theme: spacelab
    css: styles.css
    toc: true



