project:
  type: website
date: last-modified 
website:
  title: "neelsmith"
  navbar:
    background: primary
    search: true
    left:
      - href: index.qmd
        text: Home
      - text: "Digital scholarship"
        file: digschol/index.qmd     
      - text: "Why Julia?"
        file: julia.qmd
      - about.qmd

  sidebar:
    - title: "Digital scholarship"
      contents: 
        - digschol/index.qmd
        - text: "---"
        - cite/index.qmd        
        - digitexts/index.qmd
        - hmt/index.qmd        


    - title: "Orthography"
      contents:
        - digitexts/orthography/index.qmd
        - text: "---"        
        - digitexts/orthography/greek.qmd
        - digitexts/orthography/latin.qmd
        - digitexts/orthography/hebrew.qmd
        - digitexts/orthography/lycian.qmd         

    - title: "Morphological parsing"
      contents:
        - digitexts/parsing/index.qmd
        - text: "---"        
        - digitexts/parsing/kanones.qmd
        - digitexts/parsing/tabulae.qmd        

    - title: "Citable editions"
      contents:
        - digitexts/editions/index.qmd
        - text: "---"        
        - digitexts/editions/markupreaders.qmd
        - digitexts/editions/editionbuilders.qmd


    - title: "Citation with URNs"
      contents:
        - cite/urns/index.qmd
        - text: "---"          
        - cite/urns/cts.qmd
        - cite/urns/cite2.qmd   
        - cite/urns/imgs.qmd                   


    - title: "Personal"
      contents:
        - personal/index.qmd
        - text: "---"
        - personal/white.qmd
        - personal/juliagen.qmd
        

format:
  html:
    theme: spacelab
    css: styles.css
    toc: true



